import {
    ARROW_SAFE_AREA as SOURCE_ARROW_SAFE_AREA,
    CAROUSEL_ITEM_GAP as SOURCE_CAROUSEL_ITEM_GAP,
    CAROUSEL_ITEM_WIDTH as SOURCE_CAROUSEL_ITEM_WIDTH
} from 'SourceComponent/CarouselScroll/CarouselScroll.config';

// TODO: implement CAROUSEL_ITEM_GAP
export const CAROUSEL_ITEM_GAP = SOURCE_CAROUSEL_ITEM_GAP;

// TODO: implement CAROUSEL_ITEM_WIDTH
export const CAROUSEL_ITEM_WIDTH = SOURCE_CAROUSEL_ITEM_WIDTH;

// TODO: implement ARROW_SAFE_AREA
export const ARROW_SAFE_AREA = SOURCE_ARROW_SAFE_AREA;
